modLoader="javafml"
loaderVersion="[32,)"
license="GPL3"

[[mods]]
modId="tac"
version="0.2.0"
displayName="Timeless and Classics"
updateJSONURL=""
displayURL=""
authors="Timeless Development Tema"
description='''
'''

[[dependencies.tac]]
    modId="forge"
    mandatory=true
    versionRange="[32,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.tac]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.3,1.17)"
    ordering="NONE"
    side="BOTH"
[[dependencies.tac]]
    modId="obfuscate"
    mandatory=true
    versionRange="[0.6.0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.tac]]
    modId="chiselsandbits"
    mandatory=false
    versionRange="[1.0.63,)"
    ordering="NONE"
    side="BOTH"
